--- 
-
  hosts: localhost
  gather_facts: False
  vars:
    app_name: demoApp
    app_repo_version_path: "{{app_name}}/{{repo_version}}"
    git_url: "https://github.com/ravicm/waveOpsFlaskApp.git"
    deploy_dir: "/home/test2"
    app_dir: "{{deploy_dir}}/{{app_name}}"
    version_dir: "{{app_dir}}/{{repo_version}}"
    deploy_user: ubuntu 
    deploy_group: waveroot
    service_script: bin/demoapp.sh
    ami: ami-5189a661 #retrieved from aws page
    instance_type: t2.micro
    developer_name: rc 
    region: "us-west-2"
    key_name: "ravic-ubuntu"
    aws_key_path: "/home/rc/ravic-ubuntu.pem"

  tasks: 
   #Prepare the local machine
   - name:  set the git repo to be fetched
     set_fact:
         repo_version: "{{ version | default('HEAD') }}"
  
   - name:  cleaning up before start
     file: "path=/tmp{{version_dir}} state=absent"

   - name:  create a directory locally
     file: "path=/tmp{{version_dir}} state=directory mode=0755"

   - name: get the code from git to local sandbox 
     git: "repo={{ git_url }} dest=/tmp{{version_dir}}/ version={{repo_version}}"

   - name:  get the hash for git head
     shell: "cd /tmp{{version_dir}}; git rev-parse HEAD"
     register: hash 
     when: ( version is undefined )

   - name: set the repo_version to hash of the head
     set_fact:
         repo_version: "{{ hash.stdout }}"
     when: ( version is undefined )

   - name:  cleaning up before rename 
     file: "path=/tmp{{version_dir}} state=absent"

   - name: rename the HEAD directory to it's hash
     command: mv /tmp{{app_dir}}/HEAD /tmp{{version_dir}}
     when: ( version is undefined )

   - name: create a ec2 host now  
     ec2:
       key_name: "{{ key_name }}"
       instance_type: t2.micro
       image: "{{ ami }}"
       instance_tags:
             role: "{{app_name}}"
             version: "{{repo_version}}"
             owner: "{{ developer_name }}"
       group:
         - ssh
         - "{{app_name}}"
       region: "{{region}}"
       wait: yes
     register: ec2 

   - name: Wait for SSH to come up
     wait_for: host={{ec2.instances[0].private_ip}} port=22 delay=60 timeout=320 state=started

   - name: add new host to hostgroup
     add_host: hostname={{ec2.instances[0].private_ip}} groups=just_launched ansible_ssh_private_key_file={{aws_key_path}} ansible_user={{deploy_user}}

   #prepare the host
   ##name: Install system packages 
   ##name: Install user packages 
   ## make below apps go into different role
   ##name: Install application base
-
  hosts: just_launched
  remote_user: ubuntu
  vars:
    deploy_user: ubuntu 
    deploy_dir: "/home/test2"

  tasks:
   - name: install pip
     apt: name=python-pip update_cache=yes
     sudo: yes

   - name: Install Flask
     pip: name=flask 
     sudo: yes

   #deploy the application

   - name: create service directories on remote hosts 
     file: "path={{deploy_dir}} owner={{deploy_user}} group={{deploy_group}} mode=0755 state=directory"

   - name: Deploy the git files
     copy: "src=/tmp/{{version_dir}} dest={{app_dir}}"

   - name: Mark service scripts as executable 
     file: "path={{version_dir}}/{{service_script}}  mode=0755"
   
   - name: start the service now
     command: "{{version_dir}}/{{service_script}} start" 

   #start the service
   #- git: "repo=https://github.com/ravicm/waveOpsFlaskApp.git dest=/tmp/{{app_repo_version_path}}/ version={{repo_version}}"
   #- command: "sudo cp -R /tmp/{{app_repo_version_path}}/ /home/waveroot/{{app_repo_version_path}}/"
