--- 
- connection: local
  hosts: localhost
  vars:
    repo_version: 1.0.1
  tasks: 
   - ec2:
      instance_type: t2.micro
      image: ami-f7c5d496
      wait: yes
      group: ssh
      instance_tags: '{"Name":"ram"}'
      region: "us-west-2"
   - file: "path=/tmp/{{repo_version}} state=directory mode=0755"
   - git: "repo=https://github.com/ravicm/waveOpsFlaskApp.git dest=/tmp/{{repo_version}}/ version={{repo_version}}"
   - synchronize: "src=/tmp/{{repo_version}} dest=/home/waveroot/"
     sudo: yes
     sudo_user: waveroot

